### ISSUE TITLE
Adding playlist with deleted video results in unknown error in remote interface

### ISSUE THREAD

**Issue by monochrony** [regseb/castkodi#52] opened 2021-04-02 23:58 UTC
Even though the Youtube browser interface doesn't show it, this playlist contains a deleted video right at the start:
https://www.youtube.com/playlist?list=PLcoJNfD5utb3j1YlmYFwxicotYWlFugE1

Adding this playlist to Cast Kodi results in an unknown error:
https://i.imgur.com/Vx2Dw4J.jpg

Kodi plays the playlist just fine, but I can't interact with the remote interface anymore until I remove the deleted video from the playlist via the Kodi playlist menu or Kore on Android.

**Comment by regseb** [comment] 2021-04-03 16:44
@monochrony Thanks for your feedback with the problematic case.

The problem is fixed in the new version _5.11.0_ (requires Firefox _87+_).

**Comment by monochrony** [comment] 2021-04-05 16:47
Much obliged. Thanks.

**Closed** 2021-04-05 16:48 UTC
Labels: bug
